const values = {};

values.profileMenu = [
  {
    name: "Logout",
    url: "/",
  },
];
values.notific = [
  {
    name: "notification 1",
    url: "/",
  },
  {
    name: "notification 1",
    url: "/",
  },
  {
    name: "profile",
    url: "/",
  },
  {
    name: "notification 1",
    url: "/",
  },
  {
    name: "notification 1",
    url: "/",
  },
];

values.filterData = [
  {
    name: "Module",
    items: ["Eden", "Dellevue", "Eden E Tirrenia"],
  },
  {
    name: "ModuCittàle",
    count: 1,
    items: ["Eden", "Dellevue", "Eden E Tirrenia"],
  },
  {
    name: "Trasporto",
    items: ["Eden", "Dellevue", "Eden E Tirrenia"],
  },
  {
    name: "Tipi di Camera",
    items: ["Eden", "Dellevue", "Eden E Tirrenia"],
  },
];

values.requestTH = [
  "ID",
  "User Details",
  "date",
  "Module",
  "Citta",
  "Trasporto",
  "Tipi di Camera",
  "Periodo Soggiorno ",
  "price",
  "status",
];
values.requestTD = [
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: null,
    added: "",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: null,
    added: "",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
  {
    id: 2036,
    user: "James Friday",
    quote: 5,
    date: new Date(),
    module: "eden",
    citta: "Capri",
    trasporto: "Bus",
    tipi: "3 Adults, 1 Children",
    periodo: "7 notti €520 per persona | 495",
    dateLine: "27 July - 03 Aug ",
    price: 1700,
    added: "Marco",
  },
];

values.userTH = [
  "ID",
  "First Name",
  "LastName",
  "Email",
  "Phone Number",
  "Last quote sent",
  "Number of quote sent",
];

values.userTD = [
  {
    id: 2036,
    fName: "Courtney ",
    lName: "Richards",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Richards",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
  {
    id: 2036,
    fName: "Darlene",
    lName: "Warren",
    email: "arfin@example.com",
    phone: "(301) 580-7410",
    lastQuoteSent: new Date(),
    quoteSent: "03",
  },
];

export default values;
